### ISSUE TITLE
import alephinfinity1.forgeblock.config.CustomModConfig doesnt exist

### ISSUE THREAD

**Issue by ImRaddar** [AlephInfinity1/ForgeBlock#1]
When I try to build the mod it says "import alephinfinity1.forgeblock.config.CustomModConfig doesn't exist" and yeah its actually not here
did you forget to add CustomModConfig.class or something?

**Comment by AlephInfinity1** [comment]
Yea I accidentally added CustomModConfig.class into .gitignore due to .gitignore automatically ignores anything with 'config' in it. Should be fixed by now :p

**Comment by AlephInfinity1** [comment]
Also as an additional note, please don't play with this mod enabled on Hypixel. This is a recreation mod, not a helper mod.
(Wasn't expecting anybody to find this repository so I didn't add a readme.md, but thanks!)
