### ISSUE TITLE
Well im not good at coding

### ISSUE THREAD

**Issue by RKvilt** [AlephInfinity1/ForgeBlock#11]
I wanted to try this but the problem is I don't know how to launch it a tutorial would be amazing

**Comment by AlephInfinity1** [comment]
Hello, and sorry about the late reply,

To build this mod, you can download the mod from the repository. Unzip and open the folder in your system explorer. Shift + Right-click while in the explorer to open a console window. Type in './gradlew build' to build the mod (if you're running on macOS, you also have to write chmod +x gradlew first). The jar file for the mod will then appear in the 'build' folder.

I'm not the best at explaining things :p, so if you need more help, you can check out this link: [here](https://mcforge.readthedocs.io/en/latest/gettingstarted/)

Cheers, AlephInfinity1
