### ISSUE TITLE
Where exacly does it go? and what version of forge is it on I might be stupid and missed it but Im confused lol

### ISSUE THREAD

**Issue by Justice33447** [AlephInfinity1/ForgeBlock#16]

**Comment by Si1kn** [comment]
This runs on 1.15.2, and you would need to build a jar using grade.

**Comment by Justice33447** [comment]
could I have a link to grade if thats possible?

**Comment by Si1kn** [comment]
Gradle is already with the project. You need to download the source code, and in the folder with the source code, run 'gradlew build', you may need to change it, depending if your using linux, macos, or windows.

**Comment by AshlynOrSomethin** [comment]
@Justice33447 fucking dumbass
