### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by Si1kn** [AlephInfinity1/ForgeBlock#5]
Hi its me again. I found a bug which makes you crash. The method onPlayerKillEntityExp, nulls which causes it to crash. Any death will cause the crash, no matter biome, dimension, type of death. Thanks Si1kn

**Comment by AlephInfinity1** [comment]
That was caused by a missing null check in the new Experience enchantment class, sorry about that.
Fixed it just now, should be working :)
