### ISSUE TITLE
[Bug & Question] Error & Model

### ISSUE THREAD

**Issue by Si1kn** [AlephInfinity1/ForgeBlock#6]
Hi again, the error "onPlayerKillEntityExp" is nulling, and I got the fix, heres the code : ```
   if (event.getAttackingPlayer() instanceof PlayerEntity) {
            PlayerEntity player = event.getAttackingPlayer();
            player.giveExperiencePoints(event.getDroppedExperience());
        }```
, It was because if it wasn't a player, it would just crash as mobs can't take xp. I have started making minions and most of the logic is done. But I don't have a model. If you could (you don't need to) make a quick model that doesn't do anything. Thanks Si1kn

**Comment by AlephInfinity1** [comment]
Thanks for the fix, will look into them when I can!
Also as for models I'll do them ASAP, but I'm kinda busy with school atm so I might only be able to work on them on the weekends. Hope that's okay

**Comment by Si1kn** [comment]
Hey its no problem, I have a model from blockbench created, just don't know how to turn them in to entities.
